travis:
  secure:
    BINSTAR_TOKEN: KgFdvCMHHjbipeDGNuNsgpO67TjKA+LQABpzS8F3hA2cIKPSu9pdp2c/mG84c+ELz0VezV0/d0lQQDWnDwtOAyaMY0R+6SlY3l0ikt6/qJYjliPMiEZz34VqvNKMUPHeQjq1cVpX4DML667gX1KK/zAfe2XiDPfg0X+1TmSwBO487W651Mox1UwK7H5tEV0v+bciiYPBFBVgJT+jYlaguS7wOeJRiMzK8Dhgr/oPzcTaAmhfh3iQ5NaCQs4BMrX1LQo9yfoGslqy+5jVIQ0sfQbAwnF8CiwZoGve5RvGmvov+aSwBhQJlsQq4wRSKzaJICJ7uRGIMDUlrckuFH5XGaRSCdkzbFKZsfrertJTo9WMw5tjk8914M5z6pKzUzJAOkdNbhTH1Vfxe0aWSdJyS4m65TQ0c7SZqKEnAnUCjYeBylXpFIWBaSo1/eduYN7dwd84Hq73cIyvcL+K5hWu4wXecxBIlBqNWhTwy2tRFusAu7G3PYuTWj4cfgXLqV+70AY0hLluBqVXzFXzDNwBqZ4w6MqwrVi3/f1nKOHQYOOb8FLdziOiT5GxWpS10NCZ1AZIueVci/3jcVogUNKpcVbFZvjRvCrB20JOvdhfYhuFV7w8tSt/XPwZRcKDpbkdWPVNKxqv4fG7rk8TgCo62ypcHbu9QmEce5hSVgmb6a4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
